name: Docker release image

on:
  workflow_dispatch:
    inputs:
      version-core:
        description: 'Major, Minor or Patch release'
        type: choice
        required: true
        default: 'minor'
        options:
          - "major"
          - "minor"
          - "patch"

jobs:

  docker-release:
    uses: danubetech/workflows/.github/workflows/docker-release-static-version.yml@main
    with:
      GLOBAL_IMAGE_NAME: universalregistrar/driver-did-ethr
      GLOBAL_REPO_NAME: docker.io
      GLOBAL_RELEASE_VERSION: 0.1.0
      PATH_TO_DOCKERFILE: docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}